Add token deploy on NEAR with evm proof.
Near-One/bridge-sdk-rs pull request #62
Opened 2024-12-26 09:42 UTC by kisialiou

2024-12-26 09:53 UTC, olga24912 requested changes

2024-12-26 09:53 UTC, olga24912 commented on bridge-cli/src/omni_connector_command.rs
> +        .wormhole_bridge_client(None)
Why we need this change?

2024-12-26 09:53 UTC, olga24912 commented on bridge-sdk/connectors/omni-connector/src/omni_connector.rs
> +            .get_proof_for_event(tx_hash, ProofKind::DeployToken)
```suggestion
            .get_proof_for_event(tx_hash, ProofKind::LogMetadata)
```

2024-12-26 09:53 UTC, olga24912 commented on bridge-sdk/connectors/omni-connector/src/omni_connector.rs
> +            proof_kind: ProofKind::DeployToken,
```suggestion
            proof_kind: ProofKind::LogMetadata,
```

2025-01-08 07:56 UTC, kiseln commented on bridge-sdk/bridge-clients/near-bridge-client/src/near_bridge_client.rs
> +const DEPLOY_TOKEN_WITH_EVM_PROOF_DEPOSIT: u128 = 4_000_000_000_000_000_000_000_000;
Does deposit depend on which proof we are providing? If not, perhaps should be a single constant for all types

2025-01-08 07:57 UTC, kiseln approved these changes
Happy to merge and fix the comments later - up to you

2025-01-08 23:05 UTC, frolvanya commented on bridge-sdk/bridge-clients/near-bridge-client/src/near_bridge_client.rs
> +const DEPLOY_TOKEN_WITH_EVM_PROOF_DEPOSIT: u128 = 4_000_000_000_000_000_000_000_000;
Fixed in https://github.com/Near-One/bridge-sdk-rs/pull/62/commits/685daed0db26c25b7d306742ef16bd58994ee764

2025-01-08 23:05 UTC, frolvanya commented on bridge-sdk/connectors/omni-connector/src/omni_connector.rs
> +            proof_kind: ProofKind::DeployToken,
Fixed in https://github.com/Near-One/bridge-sdk-rs/pull/62/commits/685daed0db26c25b7d306742ef16bd58994ee764

2025-01-08 23:05 UTC, frolvanya commented on bridge-sdk/connectors/omni-connector/src/omni_connector.rs
> +            .get_proof_for_event(tx_hash, ProofKind::DeployToken)
Fixed in https://github.com/Near-One/bridge-sdk-rs/pull/62/commits/685daed0db26c25b7d306742ef16bd58994ee764

2025-01-08 23:06 UTC, frolvanya commented on bridge-cli/src/omni_connector_command.rs
> +        .wormhole_bridge_client(None)
We don't need to change this. Fixed in https://github.com/Near-One/bridge-sdk-rs/pull/62/commits/685daed0db26c25b7d306742ef16bd58994ee764

2025-01-08 23:06 UTC, frolvanya approved these changes

2025-01-09 07:36 UTC, olga24912 approved these changes

2025-01-09 08:20 UTC, merged